#!/bin/bash


USER_DATA=`/usr/bin/curl -s http://169.254.169.254/latest/user-data`

set -- "$USER_DATA"
IFS=","; declare -a ArrUserdata=($*)

HOSTNAME="${ArrUserdata[0]}"
DOMAIN="${ArrUserdata[1]}"
IPV4="${ArrUserdata[2]}"
NETMASKV4="${ArrUserdata[3]}"
NAMESERVER="${ArrUserdata[4]}"

# Set the host name
hostname $HOSTNAME
echo $HOSTNAME > /etc/hostname

# Add fqdn to hosts file
cat<<EOT > /etc/hosts
# This file is automatically generated by launch script
127.0.0.1 localhost
$IPV4 $HOSTNAME.$DOMAIN $HOSTNAME
EOT

# Add fqdn to hosts file
cat<<EOT > /etc/sysconfig/network
# This file is automatically generated by launch script
HOSTNAME=$HOSTNAME.$DOMAIN
NETWORKING=yes
NETWORKING_IPV6=no
IPV6INIT=no
EOT

cat <<EOT >/etc/sysconfig/network-scripts/ifcfg-eth0 
# Generated by launch script
DEVICE="eth0"
NM_CONTROLLED="no"
ONBOOT="yes"
BOOTPROTO="static"
IPADDR=$IPV4
NETMASK=$NETMASKV4
EOT
